(100000010, 'Operating Systems_all9', 'Silberstein, Adam')
(100000010, 'Operating Systems_all9', 'Silberstein, Adam')
('127.0.0.1:50002/test3db2', 0, 2, '', '', '')
 from host 127.0.0.1
 from host 127.0.0.1
 from host 127.0.0.1
input_file_string is: SELECT * FROM books;
not a join select statement
run sql file
runSQL.py: config file "test-cases/test3/test3-ms-1.cfg" read successfully
runSQL.py: connecting to host 127.0.0.1
runSQL.py: connecting to host 127.0.0.1
runSQL.py: connecting to host 127.0.0.1
runSQL.py: reading config file "test-cases/test3/test3-ms-1.cfg"
runSQL.py: recv msg success from host 127.0.0.1
runSQL.py: recv msg success from host 127.0.0.1
runSQL.py: recv msg success from host 127.0.0.1
runSQL.py: recv sql rows(100000009, 'Database Systems_all9', 'Ramakrishnan,Raghu')
runSQL.py: recv sql rows(100000009, 'Database Systems_all9', 'Ramakrishnan,Raghu')
runSQL.py: recv sql rows('127.0.0.1:50001/test3db1', 0, 1, '', '', '')
runSQL.py: send pickled data_array "[test3catdb, select nodeurl,partmtd,nodeid,partcol,partparam1,partparam2 from dtables]"
runSQL.py: send pickled data_array "[test3db1, SELECT * FROM books;]"
runSQL.py: send pickled data_array "[test3db2, SELECT * FROM books;]"
